// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS_S8Tfa_nNqH5TtrooC9EY4Be1qapIAk',
    appId: '1:146917195160:web:5ceaf0d6333e0eb644bfed',
    messagingSenderId: '146917195160',
    projectId: 'nana-project-firebase',
    authDomain: 'nana-project-firebase.firebaseapp.com',
    storageBucket: 'nana-project-firebase.firebasestorage.app',
    measurementId: 'G-CNDQ5N1D5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArd7LywEqZBrun01krgjl42be8_N_kkpo',
    appId: '1:146917195160:android:7932cf519e7f58e644bfed',
    messagingSenderId: '146917195160',
    projectId: 'nana-project-firebase',
    storageBucket: 'nana-project-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh2IB5LT3FD0gnzfYOFlPPAaXOVj4OTEo',
    appId: '1:146917195160:ios:cd43d7f866fcbe2d44bfed',
    messagingSenderId: '146917195160',
    projectId: 'nana-project-firebase',
    storageBucket: 'nana-project-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppNanaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh2IB5LT3FD0gnzfYOFlPPAaXOVj4OTEo',
    appId: '1:146917195160:ios:cd43d7f866fcbe2d44bfed',
    messagingSenderId: '146917195160',
    projectId: 'nana-project-firebase',
    storageBucket: 'nana-project-firebase.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppNanaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS_S8Tfa_nNqH5TtrooC9EY4Be1qapIAk',
    appId: '1:146917195160:web:d07734e48d43bb0144bfed',
    messagingSenderId: '146917195160',
    projectId: 'nana-project-firebase',
    authDomain: 'nana-project-firebase.firebaseapp.com',
    storageBucket: 'nana-project-firebase.firebasestorage.app',
    measurementId: 'G-6KPEV4F5PV',
  );

}